= Installation de Asciidoc et Deck.js

== Installer Ruby
Pour ceux sous windows, le plus simple est d'installer la version 2.1.6 de RubyInstaller, que vous trouverez ici : http://rubyinstaller.org/downloads/ +
Mais JRuby est également possible : http://jruby.org/download/ +  
Vérifiez que votre installation s'est bien déroulée avec un `gem -v` dans une invite de commande.

== Installer AsciiDoctor
Pour cela, dans un shell, taper la commande :

 gem install asciidoctor

[WARNING]
====
Pour ceux sous Windows, il est possible qu'à ce moment vous rencontriez l'erreur :

	ERROR:  While executing gem ... (Encoding::UndefinedConversionError)
    	U+2019 to CP850 in conversion from UTF-16LE to UTF-8 to CP850

Il s'agit d'un problème d'encodage que vous pouvez résoudre en tapant la commande :  

	chcp 1252
	
De même, si vous êtes derrière un proxy, déclarez le ainsi:

	set HTTP_PROXY=http://proxyServer:proxyPort
	set HTTP_PROXY_USER=login
	set HTTP_PROXY_PASS=password
	set HTTPS_PROXY=http://proxyServer:proxyPort
	set HTTPS_PROXY_USER=login
	set HTTPS_PROXY_PASS=password

====
Vous pouvez tester votre installation avec :

	asciidoctor --version

== Installer le backend Deck.js
La documentation d'installation et de configuration de Deck.js est disponible ici : 

* https://github.com/asciidoctor/asciidoctor-backends[]
* ou ici http://asciidoctor.org/docs/install-and-use-deckjs-backend/[] (je trouve ce lien plus clair)

Mais pour gagner du temps, voici les différentes étapes:

.	Installez les dépendances `tilt`, `haml`, `thread_safe` et `slim`

	gem install tilt haml thread_safe
	gem install slim --version 2.1.0

.	Récupérez le *backend Deck.js* pour AsciiDoctor. +
Pour cela, clonez le repo :

	git clone https://github.com/asciidoctor/asciidoctor-backends.git
+
Ou récupérez le tout sous forme de zip via GitHub. +
Ce repo contient plusieurs backends pour AsciiDoctor, dont Deck.js.
.	Créez un répertoire pour vos slides (nous l'appellerons _répertoire de travail_ par la suite).
.	Récupérez le *template de présentation* `Deck.js`.

	git clone https://github.com/imakewebthings/deck.js.git
+
Puis copiez le répertoire `deck.js` dans votre répertoire de travail.
.	Les *extensions optionnelles* de Deck.js doivent être présentes dans `deck.js/extensions` pour être actives. +
Par exemple, si vous voulez ajouter une table des matières à vos slides : 

.. récupérez la suite d'extension `deck.ext.js` de barraq via :

	git clone https://github.com/barraq/deck.ext.js.git
+
..		copier le répertoire `deck.ext.js/extensions/toc` dans le répertoire `deck.js/extensions` de votre répertoire de travail
..		(et n'oubliez pas d'ajoutez l'attribut `:toc:` dans le document header de votre .adoc (voir `Jenkins_Docker_Mesos_Marathon.adoc`))

. 	Vous pouvez maintenant *créer votre document Asciidoc* (*.adoc ou *.ad) +
Pour un exemple basique de slides, vous pouvez regarder les slides de ce repo (`Jenkins_Docker_Mesos_Marathon.adoc`), ou aller https://github.com/asciidoctor/asciidoctor-backends/blob/master/README.adoc#deckjs-source-examples[ici]
. 	Une fois le .adoc créé, générez la version formattée à l'aide de la commande:

	asciidoctor -T "<backend path>\asciidoctor-backends\haml\deckjs" -D "<output path>" -o "<generated filename>.html" -v "<source .adoc>"
+
Exemple : 

	asciidoctor -T "E:\dev\repos_Git\asciidoctor-backends\haml\deckjs" -D "E:\dev\asciidoc\generated" -o "Jenkins_Docker_Mesos_Marathon.html" -v "E:\dev\asciidoc\Jenkins_Docker_Mesos_Marathon.adoc"

. 	Il ne vous reste plus qu'à ouvrir votre .html pour lancer vos slides !

